export const stack = {
  languages: ["TypeScript", "Dart", "Kotlin", "JavaScript"],
  frontend: [
    "React",
    "Next.js",
    "Flutter",
    "React Native (Expo)",
    "Jetpack Compose",
    "Tailwind",
    "Framer Motion",
    "Three.js / R3F",
  ],
  backend: [
    "Node.js",
    "tRPC",
    "Postgres",
    "Drizzle",
    "Neon",
    "pgvector",
    "Redis",
    "Room (SQLite)",
    "JWT auth",
  ],
  ai: [
    "OpenAI Realtime",
    "Gemini Flash",
    "Anthropic SDK",
    "Vosk",
    "RAG",
    "MCP servers",
    "n8n",
  ],
  infra: [
    "AWS Lambda",
    "Cloudflare",
    "Vercel",
    "Docker",
    "Linux daemons",
    "GitHub Actions",
    "Tauri",
    "S3",
    "Daily.co",
    "Clerk",
  ],
  tools: ["Neovim", "tmux", "Claude Code", "Linear", "Figma", "Playwright"],
};
